In [ ]:
#Pandas - series and dataframes
#Dataframes - Handle the data in a table format

Level - 1

In [ ]:
#Pandas - External package
#Importing and Installing #pip install pandas

import pandas as pd


#create a dataframe
data = {'Name':['Alice','Bob'] , 'Age':[25,30]}
#variable = pd.DataFrame(<variable>)
df = pd.DataFrame(data)
df


data = [['Bharath',25],['Alice',30]]
df1 = pd.DataFrame(data,columns=['Name','Age'])
print(df)
print(df1)

    Name  Age
0  Alice   25
1    Bob   30
      Name  Age
0  Bharath   25
1    Alice   30

In [ ]:
#Reading the data from csv
df = pd.read_csv('/content/weather.csv')
#print(only 5 rows)
df.head()
df.tail()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,9.0,30.7,0.0,7.6,12.1,7,50,38,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,2,19,45,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,11,9,63,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,6,28,69,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,31,35,43,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [ ]:
#reading excel file
# df = pd.read_excel('')

#reading json file
# df = pd.read_json('/content/sample.json')
# df.head()

In [ ]:
#Save the dataframes to file
df.to_csv('test.csv')
df.to_excel('test.xlsx')
df.to_json('test.json')

In [ ]:
#Inspect the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MinTemp       366 non-null    float64
 1   MaxTemp       366 non-null    float64
 2   Rainfall      366 non-null    float64
 3   Evaporation   366 non-null    float64
 4   Sunshine      366 non-null    float64
 5   WindSpeed9am  366 non-null    int64
 6   WindSpeed3pm  366 non-null    int64
 7   Humidity9am   366 non-null    int64
 8   Humidity3pm   366 non-null    int64
 9   Pressure9am   366 non-null    float64
 10  Pressure3pm   366 non-null    float64
 11  Cloud9am      366 non-null    int64
 12  Cloud3pm      366 non-null    int64
 13  Temp9am       366 non-null    float64
 14  Temp3pm       366 non-null    float64
 15  RainToday     366 non-null    object
 16  RISK_MM       366 non-null    float64
 17  RainTomorrow  366 non-null    object
dtypes: float64(10), int64(6), object(2)
memory usage: 51.6+ KB

In [ ]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.844536,9.467213,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.539957,7.985793,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.900000,4.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

Level - 2 (Data manipulation and Cleaning)

In [ ]:
#select the single column
df['MinTemp'].head()

#multiple columns
df[['MinTemp','MaxTemp','Rainfall']]

#Specific row
#loc and iloc

#iloc ---> extract based on index
df.iloc[0:10]

#loc ---> extract based on label
df.loc[df['MinTemp'] > 20]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
72,20.9,35.7,0.0,13.8,6.9,4,17,61,28,1007.6,1003.0,7,2,23.6,34.0,No,2.0,Yes

In [ ]:
#Filtering based on conditions
#single filtering
df.loc[df['Rainfall'] > 20]

#Multiple filtering
df.loc[(df['Rainfall'] > 20) & (df['Humidity9am'] > 80)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
22,12.8,18.5,25.8,2.8,0.6,13,13,91,79,1014.0,1014.9,8,8,14.0,16.8,Yes,0.4,No
30,15.1,20.4,22.6,2.4,0.2,6,20,82,90,1015.0,1014.1,8,8,17.0,16.3,Yes,4.2,Yes

In [ ]:
#Update values based on condition
#df.loc[df[column_name]>0, <column to be updated>] = value
df.loc[df['Rainfall'] > 0, 'RainToday'] = 'Yes'

df.head(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,6,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,4,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,6,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,30,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,20,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,20,24,70,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,19,26,63,47,1024.6,1022.2,4,6,12.4,17.3,Yes,0.0,No
7,8.3,17.0,0.0,5.6,4.6,11,24,65,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,19,17,70,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,7,6,82,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [ ]:
#drop or delete
#column

df1 = df.drop(columns=['RISK_MM'])
df.drop(columns=['RISK_MM'],inplace=True)
df1.head()

#row
df.drop(index=10,inplace=True)
df.head(12)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,6,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,Yes
1,14.0,26.9,3.6,4.4,9.7,4,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,Yes
2,13.7,23.4,3.6,5.8,3.3,6,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,Yes
3,13.3,15.5,39.8,7.2,9.1,30,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,Yes
4,7.6,16.1,2.8,5.6,10.6,20,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,No
5,6.2,16.9,0.0,5.8,8.2,20,24,70,57,1023.8,1021.7,7,5,10.9,14.8,No,No
6,6.1,18.2,0.2,4.2,8.4,19,26,63,47,1024.6,1022.2,4,6,12.4,17.3,Yes,No
7,8.3,17.0,0.0,5.6,4.6,11,24,65,57,1026.2,1024.2,6,7,12.1,15.5,No,No
8,8.8,19.5,0.0,4.0,4.1,19,17,70,48,1026.1,1022.7,7,7,14.1,18.9,No,Yes
9,8.4,22.8,16.2,5.4,7.7,7,6,82,32,1024.1,1020.7,7,1,13.3,21.7,Yes,No
11,8.5,27.3,0.2,7.2,12.5,2,15,54,35,1023.8,1019.9,0,3,16.8,26.0,Yes,No
12,10.1,27.9,0.0,7.2,13.0,6,7,62,29,1022.0,1017.1,0,1,17.0,27.1,No,No

In [ ]:
#drop rows based on condition
df1 = df.loc[df['MinTemp'] > -10]
df1.loc[df1['MinTemp'] < -10].head()

Empty DataFrame
Columns: [MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

In [ ]:
# #Start manipulating the data
# #Null value checking
# #check missing values
# df.isnull().sum()
# df.loc[df['RISK_MM'] == 3.6, 'RISK_MM'] = None


# #Will drop all the rows with none values
# # df.dropna(inplace=True)

# #fill the values based on mean of the column
# df['RISK_MM'].fillna(df['RISK_MM'].mean(),inplace=True)
# df.isnull().sum()
# df.head()

In [ ]:
#Renaming the column name
df.rename(columns={'MinTemp':'MinimumTemp'},inplace=True)
df.head()

,MinimumTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,6,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,Yes
1,14.0,26.9,3.6,4.4,9.7,4,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,Yes
2,13.7,23.4,3.6,5.8,3.3,6,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,Yes
3,13.3,15.5,39.8,7.2,9.1,30,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,Yes
4,7.6,16.1,2.8,5.6,10.6,20,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,No

In [ ]:
#Sorting
df.sort_values(by='MaxTemp',ascending=False)

,MinimumTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
71,17.5,35.8,0.0,9.4,13.3,6,19,56,24,1011.8,1006.5,0,1,24.7,34.5,No,No
72,20.9,35.7,0.0,13.8,6.9,4,17,61,28,1007.6,1003.0,7,2,23.6,34.0,No,Yes
135,13.8,35.2,0.0,6.4,11.2,7,4,47,15,1022.5,1019.3,5,2,21.4,34.1,No,No
62,14.3,35.0,0.0,7.6,10.5,2,9,43,14,1012.6,1008.7,0,1,23.0,33.6,No,No
59,15.4,35.0,0.0,9.6,13.0,6,22,55,18,1017.4,1015.0,1,1,23.4,34.3,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,-0.3,9.3,0.4,1.4,9.9,9,30,72,60,1017.4,1016.6,1,1,4.7,8.3,Yes,No
251,-1.3,8.8,0.0,0.8,2.8,9,15,95,68,1020.0,1016.8,7,6,1.8,8.0,No,No
252,1.8,8.7,0.0,1.8,1.2,31,35,83,85,1014.6,1010.5,7,7,6.0,6.9,No,Yes
253,2.9,8.4,1.6,1.4,7.7,20,31,76,66,1016.7,1018.2,7,3,5.5,7.1,Yes,No
283,-3.5,7.6,0.4,2.4,4.7,30,24,92,68,1014.8,1012.6,8,6,3.3,5.1,Yes,No

Level 3 - Advanced Operations

In [ ]:
#Groupby and aggregation
df.groupby('RainToday')[['Humidity9am','Humidity3pm']].mean()
df.groupby('RainToday')[['Humidity9am','Humidity3pm']].sum()
df.groupby('RainToday')[['Humidity9am','Humidity3pm']].count()

           Humidity9am  Humidity3pm
RainToday
No                 262          262
Yes                103          103

In [ ]:
#Merge
city = pd.DataFrame({
    'Location':['Sydney','Melbourne','Delhi'],
    'Region':['NSW','VIC','ABC']
})



country = pd.DataFrame({
    'Location':['Sydney','Melbourne','Mumbai'],
    'Country':['Australia','New Zealand','India']
})

df = pd.merge(city,country,on='Location',how='inner')
df

#inner join --> it will takes only matching values from both tables
#left join ---> it will take all the values from the left table and only matched values from the right
#right join ---> it takes all the vlaues from the right and only mathing values from the left

    Location Region      Country
0     Sydney    NSW    Australia
1  Melbourne    VIC  New Zealand

In [ ]:
#how to concat the dataframes
#concat --> rows

df1 = df.iloc[0:5]
df2 = df.iloc[6:10]

#combine
df_combined = pd.concat([df1,df2],axis=0)
df_combined.head(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,6,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,4,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,6,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,30,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,20,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
6,6.1,18.2,0.2,4.2,8.4,19,26,63,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,11,24,65,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,19,17,70,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,7,6,82,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [ ]:
#concat ---> columns
temp = df[['MinTemp','MaxTemp']]
humidity = df[['Humidity9am','Humidity3pm']]

df_col_combined = pd.concat([temp,humidity],axis=1)
df_col_combined.head()

   MinTemp  MaxTemp  Humidity9am  Humidity3pm
0      8.0     24.3           68           29
1     14.0     26.9           80           36
2     13.7     23.4           82           69
3     13.3     15.5           62           56
4      7.6     16.1           68           49

In [ ]:
#Lambda
df['TempCategory'] = df['MaxTemp'].apply(lambda x: 'Hot' if x > 30 else 'Mild')
df['TempCategory'].head(20)

0     Mild
1     Mild
2     Mild
3     Mild
4     Mild
5     Mild
6     Mild
7     Mild
8     Mild
9     Mild
10    Mild
11    Mild
12    Mild
13     Hot
14     Hot
15     Hot
16     Hot
17    Mild
18     Hot
19     Hot
Name: TempCategory, dtype: object

In [ ]:
def find_category(temp):
  if temp > 30:
    return 'Hot'
  else:
    return 'Mild'

In [ ]:
df['TempCategory_1'] = df['MaxTemp'].apply(find_category)
df['TempCategory'].head(2)

0    Mild
1    Mild
Name: TempCategory, dtype: object

In [ ]:
#Date Time handling
#create a dataframe
data = {'Name':['Alice','Bob'] , 'Age':[25,30], 'DOB':['01-01-2000','04-05-2000']}
#variable = pd.DataFrame(<variable>)
df_date = pd.DataFrame(data)
df_date

    Name  Age         DOB
0  Alice   25  01-01-2000
1    Bob   30  04-05-2000

In [ ]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
 2   DOB     2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [ ]:
df_date['DOB'] = pd.to_datetime(df_date['DOB'])

In [ ]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
 2   DOB     2 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 180.0+ bytes

In [ ]:
#string operations
df_date['Name'] = df_date['Name'].str.upper()
df_date

#filtering
df_date.loc[df_date['Name'].str.startswith('A')]

    Name  Age        DOB
0  ALICE   25 2000-01-01

Performance Optimizations

In [ ]:
#query method(selecting based on loc)

rainy_days = df.query('Rainfall > 10 and Humidity9am > 80')
rainy_days

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow,TempCategory,TempCategory_1
9,8.4,22.8,16.2,5.4,7.7,7,6,82,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No,Mild,Mild
22,12.8,18.5,25.8,2.8,0.6,13,13,91,79,1014.0,1014.9,8,8,14.0,16.8,Yes,0.4,No,Mild,Mild
30,15.1,20.4,22.6,2.4,0.2,6,20,82,90,1015.0,1014.1,8,8,17.0,16.3,Yes,4.2,Yes,Mild,Mild
51,19.9,22.0,11.0,4.4,5.9,41,30,92,62,996.5,996.8,8,3,20.6,19.6,Yes,17.4,Yes,Mild,Mild
79,15.3,19.6,18.8,5.0,0.0,9,13,92,88,1008.7,1006.0,8,8,18.0,18.6,Yes,12.2,Yes,Mild,Mild
104,12.6,18.2,11.0,3.2,0.4,13,15,81,73,1010.0,1011.0,7,8,16.3,16.8,Yes,0.2,No,Mild,Mild
250,2.9,9.5,16.8,1.4,6.5,0,15,93,72,1021.6,1019.6,6,6,5.5,7.4,Yes,0.0,No,Mild,Mild
348,11.9,21.1,13.2,6.6,0.0,7,24,82,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No,Mild,Mild